
import './scss/main.scss';
import './img/arrow.png';
import './img/city.png';
import './img/john.png';
import './img/sarah.png';
import './img/velo.png';
import './img/favicon.ico';
import 'lc-switch/lc_switch.min';
import 'lc-switch/lc_switch.css';
import './components/button/button';
import './components/form-input/form-input';
import './components/dropdown/dropdown';
import './components/search/search';
import './components/calendar/calendar';
import './components/sectors/sectors';
import 'modifiable-slider/dist/main';
import 'modifiable-slider/dist/sliderm3.css';
import './components/form-toggle/form-toggle';
